version: '3.5'

services:
  nginx-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sourcetextlibrary_nginx_php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/error.log:/var/log/nginx/error.log
      - ./docker/nginx/access.log:/var/log/nginx/access.log
      - ./../Monastic-Text-Library:/var/www/html/Monastic-Text-Library
      - ./../Christian-Scripture-Library:/var/www/html/Christian-Scripture-Library
    environment:
      APP_ENV: development
      ERRORS: 1